#!/usr/bin/env node
import readlineSync from 'readline-sync';
import { randomNum, gameInit } from '../src/index.js';
import greeting from '../src/cli.js';

const isEvenTextRule = 'Answer "yes" if the number is even, otherwise answer "no".';

export const evenGame = () => {
  greeting();
  console.log(isEvenTextRule);
  for (let roundPosition = 1; roundPosition <= 3; roundPosition += 1) {
    const questionNum = randomNum(1, 100);
    const isEven = (num) => num % 2 === 0;
    const theCorrrectAnswer = isEven(questionNum) ? 'yes' : 'no';
    const enteredResponse = readlineSync.question(`Question: ${questionNum} \n `);
    const result = gameInit(theCorrrectAnswer, enteredResponse, userName, roundPosition);
    if (result === false) {
      break;
    }
  }
}